{% set name = "xtensor-python" %}
{% set version = "0.16.0" %}
{% set sha256 = "6fffe60dd66f9d909c0db3fcc1a5a652247664cad71ee78bf9861f81f6d5a31a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/QuantStack/xtensor-python/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - toolchain
    - cmake
    - xtl
    - xtensor
    - pybind11
    - numpy
  run:
    - xtl >=0.3.6,<0.4
    - xtensor >=0.14.0,<0.15
    - pybind11 >=2.1.0,<2.3
    - numpy

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
