{% set name = "xtensor-python" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/xtensor-stack/xtensor-python/archive/{{ version }}.tar.gz
    sha256: 3be09f2bc284e5a468937ad411a9976f9ab7ea5d0df40f5b1964a3694e7ee931

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11 >=2.12.0,<3                   # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make                                   # [unix]
  host:
    - python
    - xtl >=0.8,<0.9
    - xtensor >=0.26.0,<0.27
    - pybind11 >=2.12.0,<3
    - numpy
  run:
    - python
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - {{ pin_compatible('pybind11', max_pin='x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: https://xtensor-python.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
