context:
  version: "0.29.0"
  build_number: 0

package:
  name: xtensor-python
  version: ${{ version }}

source:
    url: https://github.com/xtensor-stack/xtensor-python/archive/${{ version }}.tar.gz
    sha256: 2915b220bd11b70fdd9fbb2db5f313e751189fec083e406228c8e5a31dfaa4a2

build:
  number: ${{ build_number }}

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11 >=2.12.0,<4
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - python
    - xtl >=0.8,<0.9
    - xtensor >=0.27.0,<0.28
    - pybind11 >=2.12.0,<4
    - numpy
  run:
    - python
    - ${{ pin_compatible('xtl', upper_bound='x.x') }}
    - ${{ pin_compatible('xtensor', upper_bound='x.x') }}
    - ${{ pin_compatible('pybind11', upper_bound='x') }}

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}include/xtensor-python/pyarray.hpp
          - ${{ "Library/" if win }}lib/cmake/xtensor-python/xtensor-pythonConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xtensor-python/xtensor-pythonConfigVersion.cmake

about:
  homepage: https://github.com/xtensor-stack/xtensor-python
  repository: https://github.com/xtensor-stack/xtensor-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  documentation: https://xtensor-python.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
