travis:
  secure:
    BINSTAR_TOKEN: SYzUnswga2dYToeIbGcAFsdNr9VnL9fvoHdu323uz2xHRV5S9pRMtWUXrnCfnjTlJR+hXrhq07He4U1fGer6tqkuuXC3ZZjCqZH5NuWRAME3FKIVEO7sHovAmCMcCR5xETNdRE2Uyy0dTda+DgF5Dv6ynD9tcWjfEgJjkSVA/qZi5kkbsTw7OUCbWVFEA59+yf5tjpvvPB95MrwuM7/s0yfoXdYVFtnnN/n4/4lxo3a/zSFvNjIkaaJXO7nTFAG1y5vgqoz8ewkfA/D/cHYzFDVjmyggcyTcWTNwqEv2fdo+6yEMxH+Y8zDCuxKcuG2Ve1+eCZGUBdgkjKe9bXN3bxH03pWAE6fQ5rUxcxHV8+xw0yDa1bMS6iqTZ/WodqP2n7vg1bUGF3ETinW0bibSak+JQ8ChBqiUDuPaqyDzQuIZ2VcwkIxEp8zh4gzF0xhf0W95yUR3L4NtSoiBaKE0IvcGi0dSHshkHXoS8Z8ZMhS7xrqmTTly0KRDWtDPeS3teqyjeVY8KAkaWJuX+HdbsqEVRIpJncFGwrcrmfyPtl6Hzw2TgK9FBypXN/EGQms3MD62CsIJ75DSi6uL54J2dwFC+upDRxHzYzZE8Q2v7HG8lZgxncz1k8WsbwUzR6W+pIiquuwPUyh/aQBfLcKAJk1kW5hicRns8JsUQ5JdE0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
